In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/exoplanets_raw.csv")
df.shape

(6333, 15)

In [2]:
df.head()

,pl_name,hostname,discoverymethod,disc_year,disc_facility,pl_orbper,pl_orbsmax,pl_rade,pl_bmasse,pl_orbeccen,pl_eqt,st_teff,st_rad,st_mass,sy_dist
0,XO-2 S d,XO-2 S,Radial Velocity,2024,Multiple Observatories,4696.000000,5.46000,13.000000,1179.143390,0.091,110.98,5325.0,1.020,0.980000,151.398
1,Kepler-1808 b,Kepler-1808,Transit,2021,Kepler,23.340401,0.14670,3.025113,9.400000,0.000,601.00,5530.0,0.892,0.773000,1022.010
2,Kepler-418 b,Kepler-418,Transit,2014,Kepler,86.678560,0.39249,13.450000,349.611248,0.200,434.00,5820.0,1.090,0.980000,1002.530
3,Kepler-249 d,Kepler-249,Transit,2014,Kepler,15.368459,0.09700,1.570000,3.090000,0.000,332.00,3568.0,0.482,0.510238,190.401
4,OGLE-2017-BLG-0364L b,OGLE-2017-BLG-0364L,Microlensing,2024,OGLE,NaN,3.79000,10.300000,75.800000,NaN,NaN,NaN,NaN,0.490000,7860.000

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6333 entries, 0 to 6332
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pl_name          6333 non-null   str
 1   hostname         6333 non-null   str
 2   discoverymethod  6333 non-null   str
 3   disc_year        6333 non-null   int64
 4   disc_facility    6333 non-null   str
 5   pl_orbper        5989 non-null   float64
 6   pl_orbsmax       5906 non-null   float64
 7   pl_rade          6283 non-null   float64
 8   pl_bmasse        6302 non-null   float64
 9   pl_orbeccen      5280 non-null   float64
 10  pl_eqt           5808 non-null   float64
 11  st_teff          6036 non-null   float64
 12  st_rad           6012 non-null   float64
 13  st_mass          6324 non-null   float64
 14  sy_dist          6306 non-null   float64
dtypes: float64(10), int64(1), str(4)
memory usage: 742.3 KB

In [4]:
(df.isna().sum() / len(df) * 100).sort_values(ascending=False)

pl_orbeccen        16.627191
pl_eqt              8.289910
pl_orbsmax          6.742460
pl_orbper           5.431865
st_rad              5.068688
st_teff             4.689721
pl_rade             0.789515
pl_bmasse           0.489499
sy_dist             0.426338
st_mass             0.142113
disc_year           0.000000
pl_name             0.000000
disc_facility       0.000000
hostname            0.000000
discoverymethod     0.000000
dtype: float64

In [6]:
df["disc_year"] = df["disc_year"].astype("Int64")  # Int64 con mayúscula permite nulos
df["discoverymethod"] = df["discoverymethod"].astype("category")
df["disc_facility"] = df["disc_facility"].astype("category")

In [7]:
df[["pl_bmasse", "pl_rade", "pl_orbper", "pl_orbeccen"]].describe()

         pl_bmasse      pl_rade     pl_orbper  pl_orbeccen
count  6302.000000  6283.000000  5.989000e+03  5280.000000
mean    404.629002     5.852218  7.148041e+04     0.079765
std    1140.059790     5.424010  5.196992e+06     0.152838
min       0.020000     0.309800  9.070629e-02     0.000000
25%       4.310000     1.846994  4.307440e+00     0.000000
50%       9.320000     2.860000  1.074000e+01     0.000000
75%     189.856433    11.943169  3.855830e+01     0.092000
max    9534.852210    87.205870  4.020000e+08     0.950000

In [8]:
import pathlib

out_path = pathlib.Path("../data/processed/exoplanets_clean.csv")
out_path.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(out_path, index=False)
print(f"Guardado en {out_path}")

Guardado en ..\data\processed\exoplanets_clean.csv